name: DockerBuildPushAWS

on:
  push:
    branches: [ master ]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: ${{ secrets.AWS_REGION }}
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
        - name: Build, tag, and push docker image to Amazon ECR
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
            IMAGE_TAG: amd64
          run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG-${{ github.sha }} . -f docker/Dockerfile
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG-${{ github.sha }}
            docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG-${{ github.sha }} $REGISTRY/$REPOSITORY:$IMAGE_TAG-latest
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG-latest
        # - uses: slackapi/slack-github-action@v1.18.0
        #   with:
        #     channel-id: ${{ secrets.SUGARFUNGE_SLACK_CHANNEL_ID }}
        #     payload: |
        #       {
        #         "text": "sugarfunge-status Image Updated",
        #         "blocks": [
        #           {
        #             "type": "section",
        #             "text": {
        #               "type": "mrkdwn",
        #               "text": "<https://github.com/SugarFunge/sugarfunge-status | sugarfunge-status> Image Updated :white_check_mark:\n Remember to run `docker-compose pull` to update the image if you're using the `latest` tag!"
        #             }
        #           },
        #           {
        #             "type": "section",
        #             "text": {
        #               "type": "mrkdwn",
        #               "text": "*Commit:* <${{ github.event.pull_request.html_url || github.event.head_commit.url }} | ${{ github.sha }}>"
        #             }
        #           },
        #           {
        #             "type": "section",
        #             "text": {
        #               "type": "mrkdwn",
        #               "text": "*Author:* ${{ github.event.pusher.name }}"
        #             }
        #           }
        #         ]
        #       }
        #   env:
        #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
